name: Node.js CD for staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Pre-requise for the clever-cloud deployment
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: ''
          minor-wording: '🌟,⏪'
          major-wording: 'BREAKING,:star2:'

      # Deploy
      - uses: 47ng/actions-clever-cloud@v1
        with:
          appID: app_14ec2d47-8d37-4388-9833-ea413f2841da
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
