name: Node.js CD for staging

on:
  push:
    branches:
      - staging
    paths-ignore:
      - 'package.json' #To avoid circular actions because of version bump

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Pre-requise for the clever-cloud deployment
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SPECIAL_GH_ACTIONS_TOKEN }}

      - run: git fetch --prune --unshallow

      - name: Increase version number
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.SPECIAL_GH_ACTIONS_TOKEN }}
        with:
          tag-prefix: ''
          minor-wording: ':star2:,:revert:'
          major-wording: 'BREAKING'

      - name: Deploy to Clever Cloud
        uses: 47ng/actions-clever-cloud@v1
        with:
          appID: app_14ec2d47-8d37-4388-9833-ea413f2841da
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
